### ISSUE TITLE
Colours for Links In Markdown Files

### ISSUE THREAD

**Issue by Meligy** [nycdotnet/redmond-syntax#3]
Hello,
First, thanks for both the UI and Syntax themes. They are awesome. I just love the new UI whether it's because of VS or because it's just that, awesome.

However, I do a lot of Markdown editing in Atom, and I noticed that link syntax, like:

```
[Link](http://test.com)
```

Does not get any colouring in the editor.

Same if I go to the preview in the editor, I see the link like normal text (coloured black, even though it gets an underline when hovered, which is also black).

Can you please use the blue anchor colour VS uses for links in both the editor and the preview?

Thanks a lot.

**Comment by nycdotnet** [comment]
I agree.  Fixed in v0.2.18.  Thanks for the feedback and suggestion!!

**Comment by Meligy** [comment]
Thanks a lot. You are awesome :)
