### ISSUE TITLE
Deprecated selectors in redmond-syntax/index.less

### ISSUE THREAD

**Issue by danieltaylor** [nycdotnet/redmond-syntax#5]
Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor, :host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .cursor-line, :host .cursor-line` => `atom-text-editor .cursor-line,atom-text-editor .cursor-line`

* `atom-text-editor .wrap-guide, :host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide, :host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character, :host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter, :host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded, :host .gutter .line-number.folded, atom-text-editor .gutter .line-number:after, :host .gutter .line-number:after, atom-text-editor .fold-marker:after, :host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded, atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after, atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible, :host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor, :host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region, :host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region, :host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.comment` => `.syntax--comment`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.keyword` => `.syntax--keyword`

* `.keyword.operator.cs` => `.syntax--keyword.syntax--operator.syntax--cs`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`

* `.keyword.other.ts` => `.syntax--keyword.syntax--other.syntax--ts`

* `.namespace.cs` => `.syntax--namespace.syntax--cs`

* `.namespace.cs > .keyword.operator` => `.syntax--namespace.syntax--cs > .syntax--keyword.syntax--operator

* `.storage` => `.syntax--storage`

* `.storage.modifier` => `.syntax--storage.syntax--modifier`

* `.storage.type.source` => `.syntax--storage.syntax--type.syntax--source`

* `.storage.type.generic.source` => `.syntax--storage.syntax--type.syntax--generic.syntax--source`

* `.storage.type.variable` => `.syntax--storage.syntax--type.syntax--variable`

* `.storage.type.function` => `.syntax--storage.syntax--type.syntax--function`

* `.storage.type.arrow` => `.syntax--storage.syntax--type.syntax--arrow`

* `.constant` => `.syntax--constant`

* `.constant.regexp` => `.syntax--constant.syntax--regexp`

* `.constant.escape` => `.syntax--constant.syntax--escape`

* `.constant.other.color` => `.syntax--constant.syntax--other.syntax--color`

* `.constant.other.symbol` => `.syntax--constant.syntax--other.syntax--symbol`

* `.variable.interpolation` => `.syntax--variable.syntax--interpolation`

* `.variable.parameter.function` => `.syntax--variable.syntax--parameter.syntax--function`

* `.string` => `.syntax--string`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded`

* `.string.other.link` => `.syntax--string.syntax--other.syntax--link`

* `.string > .source.js.embedded` => `.syntax--string > .syntax--source.syntax--js.syntax--embedded`

* `span .gfm.variable.mention, span .gfm.username.string, span .gfm.issue.tag, span .gfm.issue.number` => `span .syntax--gfm.syntax--variable.syntax--mention, span .syntax--gfm.syntax--username.syntax--string, span .syntax--gfm.syntax--issue.syntax--tag, span .syntax--gfm.syntax--issue.syntax--number`

* `span .punctuation.definition.gfm` => `span .syntax--punctuation.syntax--definition.syntax--gfm`

* `.punctuation.definition.variable, .punctuation.definition.parameters, .punctuation.definition.array` => `.syntax--punctuation.syntax--definition.syntax--variable, .syntax--punctuation.syntax--definition.syntax--parameters, .syntax--punctuation.syntax--definition.syntax--array`

* `.punctuation.definition.heading, .punctuation.definition.identity` => `.syntax--punctuation.syntax--definition.syntax--heading, .syntax--punctuation.syntax--definition.syntax--identity`

* `.punctuation.definition.bold` => `.syntax--punctuation.syntax--definition.syntax--bold`

* `.punctuation.definition.italic` => `.syntax--punctuation.syntax--definition.syntax--italic`

* `.punctuation.section.embedded` => `.syntax--punctuation.syntax--section.syntax--embedded`

* `.punctuation.section.method` => `.syntax--punctuation.syntax--section.syntax--method`

* `.punctuation.section.class` => `.syntax--punctuation.syntax--section.syntax--class`

* `.punctuation.separator` => `.syntax--punctuation.syntax--separator`

* `.support.class` => `.syntax--support.syntax--class`

* `.support.property-name` => `.syntax--support.syntax--property-name`

* `.link.gfm` => `.syntax--link.syntax--gfm`

* `.entity.name.class, .entity.name.type.class` => `.syntax--entity.syntax--name.syntax--class, .syntax--entity.syntax--name.syntax--type.syntax--class`

* `span .entity.gfm` => `span .syntax--entity.syntax--gfm`

* `.entity.name.section` => `.syntax--entity.syntax--name.syntax--section`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.entity.other.attribute-name.id` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.meta.class` => `.syntax--meta.syntax--class`

* `.meta.class.source` => `.syntax--meta.syntax--class.syntax--source`

* `.meta.class.source > .storage.type.source` => `.syntax--meta.syntax--class.syntax--source > .syntax--storage.syntax--type.syntax--source`

* `.meta.link` => `.syntax--meta.syntax--link`

* `.meta.require` => `.syntax--meta.syntax--require`

* `.meta.selector` => `.syntax--meta.syntax--selector`

* `.meta.property-value.css` => `.syntax--meta.syntax--property-value.syntax--css`

* `.meta.selector.css` => `.syntax--meta.syntax--selector.syntax--css`

* `.meta.separator` => `.syntax--meta.syntax--separator`

* `.none` => `.syntax--none`

* `.markup.bold` => `.syntax--markup.syntax--bold`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.italic` => `.syntax--markup.syntax--italic`

* `.markup.heading .punctuation.definition.heading` => `.syntax--markup.syntax--heading .syntax--punctuation.syntax--definition.syntax--heading`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.list` => `.syntax--markup.syntax--list`

* `.source.gfm .markup` => `.syntax--source.syntax--gfm .syntax--markup`

* `.source.gfm .markup.heading` => `.syntax--source.syntax--gfm .syntax--markup.syntax--heading`

* `.source.gfm .list` => `.syntax--source.syntax--gfm .syntax--list`

* `.source.gfm .comment` => `.syntax--source.syntax--gfm .syntax--comment`

* `.source.gfm .comment .support` => `.syntax--source.syntax--gfm .syntax--comment .syntax--support`

* `atom-text-editor[mini] .scroll-view, :host([mini]) .scroll-view` => `atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by nycdotnet** [comment]
resolved in 1.1.0
