### ISSUE TITLE
Syntax highlighting is broken

### ISSUE THREAD

**Issue by lukaskollmer** [nycdotnet/redmond-syntax#6]
As you can see, most of the code is invisible since it's rendered white on a white background.
I selected a code block to showcase this.

I'm using the [aesthetic ui](https://github.com/dtinth/atom-aesthetic-ui) theme but this applies to all themes, including the default ones like One Dark

![](https://files.lukas.vip/embed/atom-theme-error.png)

**Comment by nycdotnet** [comment]
Sorry I haven't updated this yet for new Atom and I believe it's using some deprecated selectors.  PRs accepted.
